export type { Database } from './database.types'
export type {
  CategoriaMateriaPrima,
  MateriaPrima,
  MateriaPrimaInput,
  Receta,
  RecetaInput,
  RecetaConIngredientes,
  RecetaInputCompleto,
  IngredienteReceta,
  IngredienteRecetaInput,
  LineaCalculo,
  CalculoReceta,
  UnidadMedida,
  ServiceError,
} from './catalog.types'
export type {
  EstadoEvento,
  CategoriaGasto,
  Evento,
  EventoInput,
  GastoFijo,
  GastoFijoInput,
  PlanProduccion,
  PlanProduccionInput,
  ProductoProduccion,
  ProductoProduccionInput,
  ProductoProduccionConDetalle,
  LineaProyeccion,
  ProyeccionResultado,
  DesgloseFijo,
  DesgloseVariable,
} from './events.types'
export type {
  MetodoPago,
  CategoriaImprevisto,
  CategoriaProducto,
  Producto,
  ProductoInput,
  Venta,
  VentaInput,
  VentaItem,
  VentaItemInput,
  VentaConItems,
  VentaCorreccion,
  VentaCorreccionInput,
  VentaEdicionContexto,
  GastoImprevisto,
  GastoImprevistoInput,
  CierreCaja,
  CierreCajaInput,
  LineaCarrito,
  ResumenCarrito,
  CierreInput,
  CierreResultado,
  DesgloseDia,
  DesgloseProducto,
} from './pos.types'
// METODOS_PAGO is a runtime constant (not a type) — exported as a
// value alongside the type-only re-exports above so the registrar
// dialog, edit dialog, and history dialog all source their option
// list from the same place.
export { METODOS_PAGO } from './pos.types'
export type {
  EventoProducto,
  EventoProductoConDetalle,
  CrearEventoProductoInput,
  ActualizarMargenInput,
} from './evento_productos.types'
export type {
  Socio,
  SocioInput,
  EventoSocio,
  EventoSocioInput,
  Aporte,
  AporteInput,
  CompraInsumo,
  CompraInsumoInput,
  SocioConDetalle,
  EventoSocioConDetalle,
  AporteConDetalle,
  CompraInsumoConDetalle,
  InversionSocio,
  DistribucionResultado,
  MovimientoTimeline,
} from './socios.types'
export type {
  TipoMovimiento,
  StockMovement,
  StockMovementInput,
  DerivedStock,
  RegistrarCompraInput,
  RegistrarConsumoInput,
  RegistrarCorreccionInput,
  RegistrarAjusteInput,
  RegistrarCompraInsumoInput,
  StockMovementWithMateria,
} from './stock.types'
export type {
  ProductoConfigurable,
  ProductoConfigurableInput,
  ProductoConfigurableConGrupos,
  GrupoOpciones,
  GrupoOpcionesInput,
  GrupoOpcionesConOpciones,
  OpcionGrupo,
  OpcionGrupoInput,
  AdicionalDisponible,
  AdicionalDisponibleInput,
  AdicionalDisponibleConMateriaPrima,
  VentaItemPersonalizacion,
  VentaItemPersonalizacionInput,
  PersonalizacionCarrito,
} from './configurable.types'
